version: "3"
services:
  
  backend:
    build:
      context: .
    container_name: compflask
    image: mehboobpatel/microservflask
    env_file:
      - mysql.env
    ports:
      - "5002:5000"
    networks:
      - twotier
    depends_on:
      - dbcont

  dbcont:       #host nameMYSQL_HOS
    image: mysql:5.7
    container_name: dbcont
    ports:
      - "3306:3306"
    env_file:
      - mysql.env
    # environment:
    #   MYSQL_ROOT_PASSWORD: root
    #   MYSQL_DB: myDb
    #   MYSQL_USER: admin
    #   MYSQL_PASSWORD: admin
    networks:
      - twotier
    volumes:
      - ./message.sql:/docker-entrypoint-initdb.d/anything.sql   # Mount sql script into container's /docker-entrypoint-initdb.d directory to get table automatically created
      - mysql2-data:/var/lib/mysql  # Mount the volume for MySQL data storage

volumes:
  mysql2-data:

networks:
  twotier:
