apiVersion: v1
kind: PersistentVolume
metadata:
  name: xyz #PV name
spec:
  capacity:
    storage: 256Mi
  volumeMode: Filesystem
  storageClassName: standard #must
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain #this makes the data persist
  hostPath:  #mysqldata2 or any name of folder
    path: /home/maheboob/Documents/k8snotes/flaskmysql/nol        #This is your host path where your data will be stored. Make sure to create mysqldata directory in mentioned path
