apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: abc
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Mi
  volumeName: xyz # Reference the correct PV name
