apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "admin"
            - name: MYSQL_DATABASE
              value: "lol"        #anyname u can give but it will be permnt since in pv and pvc u have given accessm
                                 #access mode is ReadWriteOnce
            - name: MYSQL_USER
              value: "admin"
            - name: MYSQL_PASSWORD
              value: "admin"
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: nol   #folder u defined in PV
              mountPath: /var/lib/mysql         # this is your container path from where your data will be stored
      volumes:
        - name: nol  #folder u defined in PV
          persistentVolumeClaim:
            claimName: abc    # PVC claim name
