apiVersion: v1
kind: PersistentVolume
metadata:
  name: xyz
spec:
  capacity:
    storage: 256Mi
  volumeMode: Filesystem
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /home/maheboob/Documents/k8snotes/flaskmysql/mysqldata2        #This is your host path where your data will be stored. Make sure to create mysqldata directory in mentioned path
